/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -k -K 
Author: AleixoAlonso (https://sketchfab.com/AleixoAlonso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/canon-at-1-retro-camera-9de66868d0f240e985da00c9480bfc82
Title: Canon AT-1 Retro Camera
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Canon_AT-1fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="#CAM0001_Body" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="#CAM0001_Battery_Check" position={[0.05, 0.001, 0.072]}>
                  <mesh name="#CAM0001_Battery_Check_#CAM0001_Textures_0" geometry={nodes['#CAM0001_Battery_Check_#CAM0001_Textures_0'].geometry} material={materials.CAM0001_Textures} />
                </group>
                <group name="#CAM0001_Spool" position={[0.05, 0.001, 0.075]}>
                  <mesh name="#CAM0001_Spool_#CAM0001_Textures_0" geometry={nodes['#CAM0001_Spool_#CAM0001_Textures_0'].geometry} material={materials.CAM0001_Textures} />
                </group>
                <group name="#CAM0001_Film_Advance" position={[-0.057, 0.001, 0.077]}>
                  <mesh name="#CAM0001_Film_Advance_#CAM0001_Textures_0" geometry={nodes['#CAM0001_Film_Advance_#CAM0001_Textures_0'].geometry} material={materials.CAM0001_Textures} />
                </group>
                <group name="#CAM0001_Shutter" position={[-0.035, -0.006, 0.076]}>
                  <mesh name="#CAM0001_Shutter_#CAM0001_Textures_0" geometry={nodes['#CAM0001_Shutter_#CAM0001_Textures_0'].geometry} material={materials.CAM0001_Textures} />
                </group>
                <group name="#CAM0001_Shutter_Speed" position={[-0.057, 0.001, 0.073]}>
                  <mesh name="#CAM0001_Shutter_Speed_#CAM0001_Textures_0" geometry={nodes['#CAM0001_Shutter_Speed_#CAM0001_Textures_0'].geometry} material={materials.CAM0001_Textures} />
                </group>
                <mesh name="#CAM0001_Body_#CAM0001_Textures_0" geometry={nodes['#CAM0001_Body_#CAM0001_Textures_0'].geometry} material={materials.CAM0001_Textures} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
