/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf -t -k -K -T 
Files: scene.gltf [16.34KB] > /Users/ginabjoraltgiske/Downloads/canon_at-1_retro_camera/scene-transformed.glb [609.42KB] (-3630%)
Author: AleixoAlonso (https://sketchfab.com/AleixoAlonso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/canon-at-1-retro-camera-9de66868d0f240e985da00c9480bfc82
Title: Canon AT-1 Retro Camera
*/

import { JSX } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props: JSX.IntrinsicElements['group']) {

    const gltf = useGLTF('/models/scene.gltf')

    return <primitive object={gltf.scene} {...props} />
}
useGLTF.preload('/models/scene.gltf')